apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-web-service
  labels:
    app: poly-yard
spec:
  replicas: 1
  selector:
    matchLabels:
      name: book-web-service
  template:
    metadata:
      labels:
        name: book-web-service
    spec:
      containers:
        - name: book-web-service
          image: "book-service:0.0.1-SNAPSHOT"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: book-web-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: book-service
  labels:
    app: poly-yard
spec:
  selector:
    name: book-web-service
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: book-web-service-config
  labels:
    app: poly-yard
data:
  SPRING_PROFILES_ACTIVE: dev

  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"
  RABBITMQ_USERNAME: guest
  RABBITMQ_PASSWORD: guest

  R2DBC_HOST: book-database
  R2DBC_PORT: "5432"
  R2DBC_DB_NAME: book_database
  R2DBC_USERNAME: postgres
  R2DBC_PASSWORD: book

  KEYCLOAK_HOST: keycloak
  KEYCLOAK_PORT: "8080"
