spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      routes:
        - id: book-service
          uri: http://localhost:8088
          predicates:
            - Path=/api/v1/me/books/**
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/poly-yard/protocol/openid-connect/certs
      client:
        registration:
          spring-gateway:
            provider: keycloak
            client-id: gateway
            client-secret: wvXxUsLTz1PdsJudFOGzqr5lqycKQSJT
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/poly-yard
server.port: 8060

logging.level:
  org.springframework.cloud.gateway: DEBUG
  org.springframework.security: DEBUG
  org.springframework.web.reactive.function.client: TRACE