review-service-host: ${REVIEW_SERVICE_HOST}
book-service-host: ${BOOK_SERVICE_HOST}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay=

  security.oauth2:
    resourceserver:
      jwt:
        jwk-set-uri: ${KEYCLOAK_HOST}/realms/polyyard/protocol/openid-connect/certs
    client:
      provider:
        keycloak:
          issuer-uri: ${KEYCLOAK_HOST}/realms/polyyard
