review-service-uri: http://${REVIEW_SERVICE_HOST}:${REVIEW_SERVICE_PORT}
book-service-uri: http://${BOOK_SERVICE_HOST}:${BOOK_SERVICE_PORT}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
  security.oauth2.resourceserver.jwt:
    jwk-set-uri: http://${KEYCLOAK_HOST}:${KEYCLOAK_PORT}/realms/polyyard/protocol/openid-connect/certs