server.port: 8000

spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      routes:
        - id: book-service
          uri: http://localhost:8002
          predicates:
            - Path=/**, /me/**,
        #- id: review-aggregator
        #  uri: http://localhost
        #  predicates:
        #      - Path=/api/reviews
        #  filters:
        #      - name: ReviewAggregatorFilter

  security.oauth2:
    resourceserver:
      jwt:
        jwk-set-uri: http://localhost:8080/realms/polyyard/protocol/openid-connect/certs
    client:
      provider:
        keycloak:
          issuer-uri: http://localhost:8080/realms/polyyard
      registration:
        auth-client:
          provider: keycloak
          client-id: back-end-client
          client-secret: PLoFGw7SYqMprSYozrY0f1OcMJyUNmMs
          authorization-grant-type: authorization_code
          scope: openid
