spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      #routes:
      #  - id: callme-service
      #    uri: http://localhost:8040
      #    predicates:
      #      - Path=/callme/**
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/spring-gateway/protocol/openid-connect/certs
      client:
        registration:
          spring-gateway:
            provider: keycloak
            client-id: spring-gateway
            client-secret: ftRaoC7r3NmqgSmdTS8tpWD88CqLEO3W
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/spring-gateway
server.port: 8060

logging.level:
  org.springframework.cloud.gateway: DEBUG
  org.springframework.security: DEBUG
  org.springframework.web.reactive.function.client: TRACE