version: "3.8"

services:
  frontend-app:
    image: hsuliz/frontend-app:1.0.0
    restart: on-failure
    ports:
      - "3000:80"
    depends_on:
      - book-microservice

  book-microservice:
    image: hsuliz/book-microservice:1.0.0
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      MONGO_HOST: mongo
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
