apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-envs
  labels:
    app: polyyard
data:
  SPRING_PROFILES_ACTIVE: dev
  REVIEW_SERVICE_HOST: review-service
  REVIEW_SERVICE_PORT: "8080"
  BOOK_SERVICE_HOST: book-service
  BOOK_SERVICE_PORT: "8080"
  KEYCLOAK_HOST: keycloak
  KEYCLOAK_PORT: "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: "gateway:0.0.1-SNAPSHOT"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: gateway-envs
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer