services:

  #gateway:
  #  build: LocalFolder/.
  #  image: review-service:0.0.1-SNAPSHOT
  #  platform: linux/amd64

  review-service:
    depends_on:
      - review-database
    build: LocalFolder/.
    image: review-service:0.0.1-SNAPSHOT
    platform: linux/amd64
    ports:
      - "8082:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev

      R2DBC_HOST: review-database
      R2DBC_PORT: 5432
      R2DBC_USERNAME: postgres
      R2DBC_PASSWORD: review
      R2DBC_DB_NAME: review

      KEYCLOAK_HOST: keycloak
      KEYCLOAK_PORT: 8080

      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest

  review-database:
    image: postgres:16-alpine
    restart: always
    shm_size: 128mb
    ports:
      - "8083:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: review


  book-service:
    depends_on:
      - book-database
    build: LocalFolder/.
    image: book-service:0.0.1-SNAPSHOT
    platform: linux/amd64
    ports:
      - "8084:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev

      R2DBC_HOST: book-database
      R2DBC_PORT: 5432
      R2DBC_USERNAME: postgres
      R2DBC_PASSWORD: book
      R2DBC_DB_NAME: book

      KEYCLOAK_HOST: keycloak
      KEYCLOAK_PORT: 8080

      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest

  book-database:
    image: postgres:16-alpine
    restart: always
    shm_size: 128mb
    ports:
      - "8085:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: book

  rabbitmq:
    image: rabbitmq:4.0-management-alpine
    container_name: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    ports:
      - "8080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command: [ "start-dev" ]