apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-microservice
  template:
    metadata:
      labels:
        app: book-microservice
    spec:
      containers:
        - name: book-microservice
          image: hsuliz/book-microservice:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_HOST
              value: mongo
          imagePullPolicy: Always