version: "3.8"

services:
  review-postgres:
    image: postgres:16-alpine
    restart: always
    shm_size: 128mb
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: review