version: "3.8"

services:
  book-db:
    container_name: book-db
    image: postgres:16-alpine
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: book