spring:
  application:
    name: book-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/poly-yard/protocol/openid-connect/certs
  data:
    mongodb:
      host: ${MONGO_HOST}
      port: 27017
      username: root
      password: example
      authentication-database: admin
      auto-index-creation: true
server:
  error:
    include-message: always
  port: 8088
