spring:
  application:
    name: book-service
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: example
      authentication-database: admin
      auto-index-creation: true
