server.port: 8002
spring:
  application:
    name: book-service
  security.oauth2.resourceserver.jwt.jwk-set-uri: http://localhost:8080/realms/polyyard/protocol/openid-connect/certs
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: example
      authentication-database: admin
      auto-index-creation: true
server:
  error:
    include-message: always

logging.level:
  org.springframework.cloud.gateway: DEBUG
  org.springframework.security: DEBUG
  org.springframework.web.reactive.function.client: TRACE