apiVersion: v1
kind: ConfigMap
metadata:
  name: review-service-config
  labels:
    app: review-service
data:
  SPRING_PROFILES_ACTIVE: dev

  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"
  RABBITMQ_USERNAME: review
  RABBITMQ_PASSWORD: review

  R2DBC_HOST: review-database
  R2DBC_PORT: "5432"
  R2DBC_DB_NAME: review_database
  R2DBC_USERNAME: postgres
  R2DBC_PASSWORD: review

  KEYCLOAK_HOST: keycloak
  KEYCLOAK_PORT: "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-service
  template:
    metadata:
      labels:
        app: review-service
    spec:
      containers:
        - name: review-service
          image: "review-service:0.0.1-SNAPSHOT"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: review-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: review-service
spec:
  selector:
    app: review-service
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer