name: Build backend services

on:
  pull_request:
  push:
    branches:
      - main
      - feature/*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend-services
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: oracle
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Test Report
        uses: test-summary/action@v2
        with:
           paths: "review-service/build/test-results/test/TEST-dev.hsuliz.polyyard.service.review.service.ReviewServiceIntegrationTest.xml" 

