name: Build backend services

on:
  pull_request:
  push:
    branches:
      - main
      - feature/*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend-services
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: oracle
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Assemble
        run: ./gradlew assemble

      - name: Test
        run: ./gradlew test

      - name: Test2
        if: always()
        run: ls

      - name: Test3
        if: always()
        run: ls review-service/build

      - name: Test4
        if: always()
        run: ls review-service/build/test-results

      - name: Test5
        if: always()
        run: ls review-service/build/test-results/test

      - name: Test Report
        if: always()
        uses: test-summary/action@v2
        with:
          paths: "review-service/build/test-results/test/*.xml"

