name: Build backend services

on:
  pull_request:
  push:
    branches:
      - main
      - feature/*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: oracle
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Assemble
        working-directory: ./backend-services
        run: ./gradlew assemble

      - name: Test
        working-directory: ./backend-services
        run: ./gradlew test

      - name: Test summary
        if: always()
        uses: test-summary/action@v2
        with:
          paths: "./backend-services/review-service/build/test-results/test/TEST-*.xml"
          output: test-summary.md
        
      - name: Add test summary to build summary
        if: always()
        run: |
          echo "#### Test Summary" >> $GITHUB_STEP_SUMMARY
          cat test-summary.md >> $GITHUB_STEP_SUMMARY
        
        

